### ISSUE TITLE
About Appendix

### ISSUE THREAD

**Issue by NickChang97** [xieenze/DetCo#5]
Hi, really interesting work! In your paper, you mentioned there is a appendix. How can I find it? Thanks in advance.

**Comment by xieenze** [comment]
Hi  
Thanks for the interest. Maybe I forget to upload it in arxiv. The appendix is attachment. Please check. I will update a arxiv version soon.




On 09/9/2021 10:06，Qing ***@***.***> wrote：

Hi, really interesting work! In your paper, you mentioned there is a appendix. How can I find it? Thanks in advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NickChang97** [comment]
Get it, really thanks for your quick reply.

**Comment by NickChang97** [comment]
Really sorry to mention it again, while I can't stiil find the updated version

**Comment by mrsempress** [comment]
I'm sorry that I can't find the appendix yet.
